name: policy-evaluation
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.12.*
  - numpy = 2.1.*
  - pandas = 2.2.*
  - matplotlib = 3.9.*
  - pip = 24.2.*
  - seaborn
  - scikit-learn = 1.5.*
  - xgboost = 2.1.*
  - pyreadr = 0.5.*
  - scipy = 1.14.*